---
version: 2

before:
  hooks:
    - ./boot.sh

builds:
  - id: tc_cpumap
    binary: tc_cpumap
    main: ./cmd/tc_cpumap
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
  - id: tc_cpumap_config
    binary: tc_cpumap_config
    main: ./cmd/config
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
  - id: tc_cpumap_trafficstats
    binary: tc_cpumap_trafficstats
    main: ./cmd/trafficstats
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
  - id: tc_cpumap_exporter
    binary: tc_cpumap_exporter
    main: ./cmd/exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ldflags:
      - >
          -s
          -w
          -X "github.com/prometheus/common/version.Version={{ .Version }}"
          -X "github.com/prometheus/common/version.Revision={{ .Commit }}"
          -X "github.com/prometheus/common/version.BuildDate={{ .Date }}"
          {{- if index .Env "GITHUB_REF_NAME" }}
          -X "github.com/prometheus/common/version.Branch={{ .Env.GITHUB_REF_NAME }}"
          -X "github.com/prometheus/common/version.BuildUser={{ .Env.BUILD_USER }}"
          {{- end }}

checksum:
  name_template: "checksums.txt"

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
